#!/usr/bin/env bash


NOTE_DIR="/home/$USER/.cache/note-grep"

TODAY=$(date +%d-%m-%y)
FILE="$NOTE_DIR/$TODAY.yml"

if [ ! -s $FILE ]; then
  echo "File does not exist, creating new file:"
  echo '---' > $FILE
fi

$EDITOR $FILE
